Update index.js
PerformanC/FastLink pull request #1
Opened 2023-05-20 20:53 UTC by TehPigYT

update conditions

2023-05-20 20:54 UTC, ThePedroo requested changes
No need to add == undefined in all of them, only in debug

2023-05-20 20:55 UTC, TehPigYT commented
just did it to make them similar

2023-05-20 20:57 UTC, ThePedroo commented
Oh yes, but the rest of them need to have a value, but debug can't be either null or undefined, in the case would be better verifying if it's a boolean if contains a value

2023-05-22 18:56 UTC, ThePedroo approved these changes

2023-05-22 18:58 UTC, merged