Code Improvements
PerformanC/FastLink pull request #3
Opened 2023-12-08 14:40 UTC by TehPigYT

## Changes

+ Added Loop function again
+ Added shuffle function again
/ Made some minor code changes

## Why 

## Checkmarks

- [X] The modified functions have been tested.
- [X] Used the same indentation as the rest of the project.

## Additional information

2023-12-15 13:11 UTC, ThePedroo requested changes
Save that, LGTM. I still didn't test though, I'll be doing it after those changes.

2023-12-15 13:11 UTC, ThePedroo commented on index.js
> +    return Players[this.guildId].loop = loop;
Could you remove the [semicolon?](https://github.com/PerformanC/contributing#javascript--typescript-nodejs)

2023-12-15 13:11 UTC, ThePedroo commented on src/events/track/trackEnds.js
> +      if(player.loop === 'track') player.queue.unshift(player.queue[0]);
if requires a space between the ( and the if. Also the semicolon.

2023-12-15 13:11 UTC, ThePedroo commented on index.js
> +    if (Players[this.guildId].queue.length < 3) return false
To be consistent with skipTrack, could you move the return to the line below?

2023-12-18 21:29 UTC, TehPigYT commented on index.js
> +    return Players[this.guildId].loop = loop;
Done in [e267b13](https://github.com/PerformanC/FastLink/pull/3/commits/e267b138d9ddb766f7fa48804d91d9a03cf07a55)

2023-12-18 21:29 UTC, TehPigYT commented on index.js
> +    if (Players[this.guildId].queue.length < 3) return false
Done in [e267b13](https://github.com/PerformanC/FastLink/pull/3/commits/e267b138d9ddb766f7fa48804d91d9a03cf07a55)

2023-12-18 21:33 UTC, TehPigYT commented on src/events/track/trackEnds.js
> +      if(player.loop === 'track') player.queue.unshift(player.queue[0]);
Unfortunately the changes cannot be committed because GitHub shows an error message saying that the file cannot be edited.

2024-01-14 04:52 UTC, ThePedroo approved these changes

2024-01-14 04:53 UTC, merged